name: Hired Gun Media
favicon: null
layout_spectrum: 0.96021
typography_spectrum: 0.38514
title: Hired Gun Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff76ff'
    - '#7f51ff'
    - '#110326'
    - '#ff5752'
    - '#a91f50'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
